// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj09Tevl-TTCrgQi2ga__Kugex4Hp_x28',
    appId: '1:461488887549:web:99aaedada2f83494595094',
    messagingSenderId: '461488887549',
    projectId: 'quiz-77801',
    authDomain: 'quiz-77801.firebaseapp.com',
    storageBucket: 'quiz-77801.firebasestorage.app',
    measurementId: 'G-Z6SQGYV4D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSV1RX1kKKWuQjKJG3Im6TJF_Pnk8pxQ',
    appId: '1:461488887549:android:b73166ab7ce3b967595094',
    messagingSenderId: '461488887549',
    projectId: 'quiz-77801',
    storageBucket: 'quiz-77801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXmMc4m6vsC8OzyVAwMBzF5WkQZz6w1E',
    appId: '1:461488887549:ios:5873188633fddf8a595094',
    messagingSenderId: '461488887549',
    projectId: 'quiz-77801',
    storageBucket: 'quiz-77801.firebasestorage.app',
    iosBundleId: 'com.example.quizfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXmMc4m6vsC8OzyVAwMBzF5WkQZz6w1E',
    appId: '1:461488887549:ios:5873188633fddf8a595094',
    messagingSenderId: '461488887549',
    projectId: 'quiz-77801',
    storageBucket: 'quiz-77801.firebasestorage.app',
    iosBundleId: 'com.example.quizfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj09Tevl-TTCrgQi2ga__Kugex4Hp_x28',
    appId: '1:461488887549:web:a372e691997bf6ae595094',
    messagingSenderId: '461488887549',
    projectId: 'quiz-77801',
    authDomain: 'quiz-77801.firebaseapp.com',
    storageBucket: 'quiz-77801.firebasestorage.app',
    measurementId: 'G-TWY03C11E1',
  );
}
